version: "3.7"
services:
  backend:
    build:
      context: ./backend-repo
    restart: unless-stopped
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend-repo:/code
    ports:
      - 8000:8000
    env_file:
      - ./backend-repo/.env
