version: "3.7"
services:
  backend:
    build:
      context: ./backend-repo
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    restart: unless-stopped
    # command: python backend/manage.py runserver 0.0.0.0:8000 # nomal start
    command: sh -c "cd backend/ && gunicorn wpyw.wsgi:application --bind 0.0.0.0:8000" # gunicorn start
    volumes:
      - ./backend-repo:/code
    ports:
      - 8000:8000
    env_file:
      - ./backend-repo/.env
    depends_on:
      - nginx

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./wpyw/static:/static
    ports:
      - 80:80
