global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: backend
    metrics_path: api/metrics
    static_configs:
      - targets:
          - localhost :8000
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node-exporter
    static_configs:
      - targets:
          ["localhost:9090", "localhost:9100", "localhost:80", "localhost:8000"]
